// This file is auto-generated by Inliner. Do not edit manually.
#ifndef IMAGE_STORE_FOCUSED_CHI_SQUARED_ICON_H
#define IMAGE_STORE_FOCUSED_CHI_SQUARED_ICON_H

#include <escher/image.h>

namespace ImageStore {

extern const Image * FocusedChiSquaredIcon;

};

#endif
