// This file is auto-generated by Inliner. Do not edit manually.
#ifndef IMAGE_STORE_COMPUTER_H
#define IMAGE_STORE_COMPUTER_H

#include <escher/image.h>

namespace ImageStore {

extern const Image * Computer;

};

#endif
