#ifndef ION_SIMULATOR_WINDOWS_IMAGES_H
#define ION_SIMULATOR_WINDOWS_IMAGES_H

// This file is auto-generated by resgen.py


class ResourceID {
public:
  constexpr ResourceID(const char * identifier, int id) : m_identifier(identifier), m_id(id) {}
  const char * identifier() const { return m_identifier; }
  int id() const { return m_id; }
private:
  const char * m_identifier;
  int m_id;
};

static constexpr ResourceID resourcesIdentifiers[] = {
ResourceID("background.jpg", 1000),
ResourceID("horizontal_arrow.png", 1001),
ResourceID("vertical_arrow.png", 1002),
ResourceID("round.png", 1003),
ResourceID("small_squircle.png", 1004),
ResourceID("large_squircle.png", 1005),
};

#endif
